# info globale de docs
# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList

server:  
  http_listen_port: 9080  
  grpc_listen_port: 0 

positions:  
  filename: /tmp/positions.yaml  # Fichier local où Promtail enregistre sa position de lecture dans les logs 

clients: 
  - url: http://loki:3100/loki/api/v1/push  

scrape_configs:  
  - job_name: flog_scrape  
    docker_sd_configs:  # Utilisation de la découverte de services Docker pour collecter les logs
      - host: unix:///var/run/docker.sock  # Utilisation de la socket Docker pour interagir avec le daemon Docker local
        refresh_interval: 5s  
        filters:  
          - name: label  
            values: ["logging=promtail"]  # selectionne unique promtail pour les logs

    relabel_configs: 
      - source_labels: ['__meta_docker_container_name']  # Utilisation du nom du conteneur comme source
        regex: '/(.*)'  # Extraction du nom sans le préfixe "/"
        target_label: 'container'  # Le nom du conteneur sera utilisé dans le label "container"
      - source_labels: ['__meta_docker_container_log_stream']  # Utilisation du flux de log du conteneur Docker
        target_label: 'logstream'  # Assigne ce flux de log au label "logstream"
      - source_labels: ['__meta_docker_container_label_logging_jobname']  # Utilisation de l'étiquette Docker "logging_jobname"
        target_label: 'job'  # Affecte cette étiquette au label "job" dans Loki

    pipeline_stages:  
      - cri: {}  # permet de 'parser' les logs en format CRI
      - multiline:  #
          firstline: ^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}  # Détecte une ligne de début de log avec un timestamp 
          max_wait_time: 3s  

      # https://grafana.com/docs/loki/latest/clients/promtail/stages/json/
      - json: 
          expressions:  
            level: level  # Extrait le champ "level" du log 
